### PR TITLE
Detection of Python's standard libraries

### PR DESCRIPTION
**Pull request by fridex**

### CODE REVIEW

**Comment by fridex** [comment]
> BTW: WDYT about excluding **builtins** as well? Something like `--without-builtins`?

Which builtins do you mean? Give me an example?

**Comment by CermakM** [comment]
There is a difference between standard libraries and builtins. For example `sys` ... currently, it wouldn't be filtered out by `--without-standard-imports`

**Comment by fridex** [comment]
> There is a difference between standard libraries and builtins. For example `sys` ... currently, it wouldn't be filtered out by `--without-standard-imports`
> 
> For more libraries which are considered to be builtins check out:
> 
> ```python
> import sys
> print(sys.builtin_module_names)
> ```

The algorithm of `invectio` is import based - it detects used functions and attributes based on import statements which are matched to libraries. I believe builtins are in that case automatically excluded. Let me know if you've spotted detection of a builtin though.

**Comment by CermakM** [comment]
Yes, the are detected.

**Comment by fridex** [comment]
> Yes, they are detected.
> 
> Example:
> 
> ```shell
> ./invectio-cli sample.py --without-standard-imports
> ```
> 
> ```json
> {
>   "report": {
>     "sample.py": {
>       "cufflinks": [
>         "cufflinks.go_offline"
>       ],
>       "pandas": [
>         "pandas.set_option"
>       ],
>       "plotly": [
>         "plotly.offline.init_notebook_mode"
>       ],
>       "sys": [
>         "sys.path.insert"
>       ],
>       "thoth": [
>         "thoth.storages.InspectionResultsStore"
>       ]
>     }
>   },
>   "version": "0.0.5"
> }
> ```

Could you open an RFE issue with a reproducer in that case? Thanks.

**Comment by CermakM** [comment]
https://github.com/thoth-station/invectio/issues/26

**Pull request merged**
